services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_DB: my_ShoppingList
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5433:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
  backend:
    image: backend-cs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__default=Host=postgres;Database=my_ShoppingList;Username=postgres;Password=postgres;
    ports:
      - 9051:8080
    depends_on:
      - postgres
  frontend:
    image: shoppinglist-react-app
    ports:
        - 5173:5173
    depends_on:
      - backend

volumes:
    postgres-data:
