version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_DB: my_ShoppingList
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5433:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: